### PR TITLE
update docker image

### PR DESCRIPTION
**Pull request by peterus**
I am working on #115 and I wanted to share the first draft.
It is already running on my lokal machine. please dubble check and make some comments if you are not or happy with the changes.
There are still a lot of lines commented out, I will remove them when you are fine with it - as an example: do you need gdb in the docker image? etc.

### CODE REVIEW

**Comment by peterus** [comment]
the failing CI check is because of the change in the docker image which hast to be re-generated.

**Comment by PerMalmberg** [comment]
Welcome, new contributor :)

You can temporarily push your docker image to docker hub and update the build script to use that image to ensure it also passes in CI. Once done, it can be reverted and I'll push a new image based on the changes which will make this PR pass.

gdb isn't really needed in the image, no.

**Comment by peterus** [comment]
@PerMalmberg all green :)

**Comment by PerMalmberg** [comment]
Great. Revert the image, remove the commented stuff and I'll merge and push an updated 'official' smooth build image.

**Comment by peterus** [comment]
i reverted the docker image change and removed the not needed lines in the docker file. From my side it is ready to merge.

**Pull request merged**
